name: passenger_transportation_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^4.0.0
  grpc: ^4.0.4
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  archive: ^3.4.9
  fixnum: ^1.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  permission_handler: ^11.0.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.14
  flutter_osm_plugin: ^1.3.7
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  protoc_plugin: ^22.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/gtfs_rapid_rail_kl/stops.txt
    - assets/gtfs_rapid_rail_kl/stop_times.txt
    - assets/gtfs_rapid_rail_kl/routes.txt
    - assets/gtfs_rapid_rail_kl/trips.txt
    - assets/images/
    - assets/images/grab_logo.png

# Proto generation configuration
protoc:
  output: protos/
