name: passenger_transportation_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^4.0.0
  grpc: ^4.0.4
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  archive: ^4.0.7
  fixnum: ^1.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^14.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  url_launcher: ^6.1.12
  flutter_osm_plugin: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  protoc_plugin: ^22.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
